# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case_interface_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICaseDescription', models.CharField(max_length=150)),
                ('ICaseURL', models.CharField(max_length=150)),
                ('ICaseMethod', models.CharField(max_length=150)),
                ('ICase_Data', models.CharField(max_length=20000)),
                ('ICase_ExResult', models.CharField(max_length=20000)),
                ('Icase_CreateUser', models.CharField(max_length=150)),
                ('IcaseFiled1', models.CharField(max_length=500)),
                ('IcaseFiled2', models.CharField(max_length=500)),
                ('IcaseFiled3', models.CharField(max_length=500)),
                ('IcaseFiled4', models.CharField(max_length=500)),
                ('IcaseFiled5', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='run_interface_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IRunDateTime', models.DateTimeField()),
                ('IRunResult', models.CharField(max_length=150)),
                ('IRunUser', models.CharField(max_length=150)),
                ('IRunReportName', models.CharField(max_length=150)),
                ('IRunFiled1', models.CharField(max_length=500)),
                ('IRunFiled2', models.CharField(max_length=500)),
                ('IRunFiled3', models.CharField(max_length=500)),
                ('IRunFiled4', models.CharField(max_length=500)),
                ('IRunFiled5', models.CharField(max_length=500)),
            ],
        ),
    ]
