# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case_interface_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICaseDescription', models.CharField(max_length=150)),
                ('ICaseURL', models.CharField(max_length=150)),
                ('ICaseMethod', models.CharField(max_length=150)),
                ('ICase_Data', models.TextField()),
                ('ICase_ExResult', models.TextField()),
                ('Icase_CreateUser', models.CharField(max_length=150)),
                ('IcaseFiled1', models.CharField(max_length=500)),
                ('IcaseFiled2', models.CharField(max_length=500)),
                ('IcaseFiled3', models.CharField(max_length=500)),
                ('IcaseFiled4', models.CharField(max_length=500)),
                ('IcaseFiled5', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='run_interface_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICaseNo', models.IntegerField()),
                ('IRunDateTime', models.DateTimeField(auto_now=True)),
                ('IRunResult', models.CharField(max_length=150)),
                ('IRunUser', models.CharField(max_length=150)),
                ('IRunReportName', models.CharField(max_length=150)),
                ('IRunFiled1', models.CharField(max_length=500)),
                ('IRunFiled2', models.CharField(max_length=500)),
                ('IRunFiled3', models.CharField(max_length=500)),
                ('IRunFiled4', models.CharField(max_length=500)),
                ('IRunFiled5', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('e_mail', models.CharField(max_length=150)),
            ],
        ),
    ]
