# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_interface_table',
            name='ICase_Data',
        ),
        migrations.RemoveField(
            model_name='case_interface_table',
            name='ICase_ExResult',
        ),
    ]
