# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0003_auto_20180316_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_interface_table',
            name='ICase_Data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case_interface_table',
            name='ICase_ExResult',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
